#! /usr/bin/env sh

test_shell(){
     # TODO: to check the docker image is built or not
    if [ -z "$(docker images -q xcmd/debian:latest)" ]; then
        echo "docker image xcmd/debian:latest is not built"
        exit 1
    fi

    echo "Testing cross-shell"
    echo "=================="
    echo "Testing debian dash mawk run: $*"
    docker run -it -v "$(pwd)":/pd xcmd/debian sh -c ". ~/.x-cmd/.boot/boot && cd pd && eval "$(curl https://get.x-cmd.com/all)" && $*"

    echo "Testing alpine ash busybox awk run: $*"
    docker run -it -v "$(pwd)":/pd xcmd/alpine sh -c ". ~/.x-cmd/.boot/boot && cd pd && eval "$(curl https://get.x-cmd.com/all)" && $*"

    echo "Testing bash 3 busybox awk run: $*"
    docker run -it -v "$(pwd)":/pd xcmd/bash:3 bash -c ". ~/.x-cmd/.boot/boot && cd pd && eval "$(curl https://get.x-cmd.com/all)" && $*"

    echo "Testing bash 4 busybox awk run: $*"
    docker run -it -v "$(pwd)":/pd xcmd/bash:4 bash -c ". ~/.x-cmd/.boot/boot && cd pd && eval "$(curl https://get.x-cmd.com/all)" && $*"

    echo "Testing bash 5 busybox awk run: $*"
    docker run -it -v "$(pwd)":/pd xcmd/bash:5 bash -c ". ~/.x-cmd/.boot/boot && cd pd && eval "$(curl https://get.x-cmd.com/all)" && $*"

    echo "Testing centos bash5 busybox gawk run: $*"
    docker run -it -v "$(pwd)":/pd xcmd/centos bash -c ". ~/.x-cmd/.boot/boot && cd pd && eval "$(curl https://get.x-cmd.com/all)" && $*"

    # Test it in windows/mac
    eval "$*"
}

test() {
    test_shell "stat --version"
}
