#! /usr/bin/env sh
build() {
    docker build --no-cache -t xcmd/debian:latest -f ./docker/debian.Dockerfile .
    docker build --no-cache -t xcmd/alpine:latest -f ./docker/alpine.Dockerfile .
    docker build --no-cache -t xcmd/bash:3 -f ./docker/bash3.Dockerfile .
    docker build --no-cache -t xcmd/bash:4 -f ./docker/bash4.Dockerfile .
    docker build --no-cache -t xcmd/bash:5 -f ./docker/bash5.Dockerfile .
}

test_shell(){

    # TODO: to check the docker image is built or not
    if [ -z "$(docker images -q xcmd/debian:latest)" ]; then
        build
    fi

    docker run -it -v "$(pwd)":/pd xcmd/debian bash -c ". ~/.x-cmd/boot && cd pd && $*"
    docker run -it -v "$(pwd)":/pd xcmd/alpine sh -c ". ~/.x-cmd/boot && cd pd && $*"
    docker run -it -v "$(pwd)":/pd xcmd/bash:3 bash -c ". ~/.x-cmd/boot && cd pd && $*"
    docker run -it -v "$(pwd)":/pd xcmd/bash:4 bash -c ". ~/.x-cmd/boot && cd pd && $*"
    docker run -it -v "$(pwd)":/pd xcmd/bash:5 bash -c ". ~/.x-cmd/boot && cd pd && $*"
}

test() {
    test_shell "stat --version"
}
